---
- name: Install Apps
  hosts: local
  roles:
    - apps
  tags: apps

- name: Install git
  hosts: local
  roles:
    - git
  tags: git

- name: Install npm
  hosts: local
  roles:
    - npm
  tags: npm

- name: Install php
  hosts: local
  roles:
    - php
  tags: php

- name: Install composer
  hosts: local
  roles:
    - composer
  tags: composer

- name: Install valet
  hosts: local
  roles:
    - valet
  tags: valet

- name: Install vscode
  hosts: local
  roles:
    - vscode
  tags: vscode

- name: Backup stuff
  hosts: local
  roles:
    - mackup
  tags: backup

- name: Setup OSX preferences
  hosts: local
  roles:
    - osx
  tags: osx

- name: Symlinks
  hosts: local
  roles:
    - symlinks
  tags: links

- name: Projects
  hosts: local
  roles:
    - projects
  tags: projects

- name: Set up local development environment
  hosts: local
  roles:
    - apps
    - mackup
    - osx
    - git
    - npm
    - php
    - composer
    - valet
    - symlinks
    - projects
    - vscode
  tags: boostrap
