- name: Install mackup
  homebrew: name=mackup state=present

- name: Create symblink from home folder
  file: path={{ home }}/.mackup.cfg src={{ home }}/dotfiles/roles/mackup/templates/mackup.cfg state=link force=yes

- name: Create backup directory
  file: path="{{ home }}/Google Drive/backup" state=directory

- name: Backup files
  shell: mackup backup