- name: Install node and npm with homebrew
  homebrew: name=node state=latest

- name: Install common npm utilities
  npm: name={{item}} state=present global=yes
  with_items: '{{npm_global_packages}}'
