- homebrew:
    update_homebrew: yes
    upgrade_all: yes
    
- name: Install apps with Homebrew
  homebrew: name={{item}} state=present
  with_items: '{{apps_homebrew}}'

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{item}} state=present
  with_items: '{{apps_cask}}'
